language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

notifications:
  webhooks:
    urls:
      - https://integrations.bonbotics.io/travis/webhook/HI2kVoT0VXcNE6zRZvGc1aKvbiJxjkQ97RlGR55LD5E
    on_success: always
    on_failure: always
    on_start: never

# command to run tests
script:
  - pytest app.py
